# Generated by Django 4.2.27 on 2026-01-24 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icon')),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Danh mục kiến thức',
                'verbose_name_plural': 'Danh mục kiến thức',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('excerpt', models.TextField(blank=True, max_length=500, verbose_name='Tóm tắt')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('language', models.CharField(choices=[('en', 'Tiếng Anh'), ('de', 'Tiếng Đức'), ('all', 'Tất cả ngôn ngữ')], default='all', max_length=5, verbose_name='Ngôn ngữ')),
                ('level', models.CharField(choices=[('A1', 'A1 - Sơ cấp'), ('A2', 'A2 - Sơ trung'), ('B1', 'B1 - Trung cấp'), ('B2', 'B2 - Trung cao'), ('C1', 'C1 - Cao cấp'), ('C2', 'C2 - Thành thạo'), ('all', 'Mọi trình độ')], default='all', max_length=5, verbose_name='Trình độ')),
                ('cover_image', models.ImageField(blank=True, upload_to='knowledge/covers/')),
                ('thumbnail', models.ImageField(blank=True, upload_to='knowledge/thumbnails/')),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('canonical_url', models.URLField(blank=True)),
                ('og_title', models.CharField(blank=True, max_length=95)),
                ('og_description', models.CharField(blank=True, max_length=200)),
                ('og_image', models.ImageField(blank=True, upload_to='knowledge/og/')),
                ('schema_type', models.CharField(choices=[('Article', 'Article'), ('HowTo', 'HowTo (Hướng dẫn)'), ('FAQPage', 'FAQ Page'), ('Course', 'Course')], default='Article', help_text='Loại structured data cho Google', max_length=20, verbose_name='Schema Type')),
                ('is_published', models.BooleanField(default=False, verbose_name='Đã xuất bản')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Nổi bật')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_articles', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='knowledge.category', verbose_name='Danh mục')),
            ],
            options={
                'verbose_name': 'Bài viết kiến thức',
                'verbose_name_plural': 'Bài viết kiến thức',
                'ordering': ['-is_featured', '-published_at', '-created_at'],
            },
        ),
    ]
