# Generated by Django 4.2.27 on 2026-02-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_knowledgearticle_ai_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgearticle',
            name='cover_image_srcset',
            field=models.JSONField(blank=True, default=dict, help_text='Auto-generated responsive image URLs', verbose_name='Responsive images'),
        ),
    ]
