# Generated by Django 4.2.27 on 2026-01-24 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('icon', models.CharField(blank=True, help_text='Tên icon (VD: FaNewspaper)', max_length=50, verbose_name='Icon')),
                ('meta_title', models.CharField(blank=True, help_text='Tiêu đề hiển thị trên Google (tối đa 70 ký tự)', max_length=70, verbose_name='SEO Title')),
                ('meta_description', models.CharField(blank=True, help_text='Mô tả hiển thị trên Google (tối đa 160 ký tự)', max_length=160, verbose_name='SEO Description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Danh mục tin tức',
                'verbose_name_plural': 'Danh mục tin tức',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('excerpt', models.TextField(blank=True, help_text='Đoạn giới thiệu ngắn (hiển thị trong danh sách)', max_length=500, verbose_name='Tóm tắt')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('cover_image', models.ImageField(blank=True, upload_to='news/covers/', verbose_name='Ảnh bìa')),
                ('thumbnail', models.ImageField(blank=True, upload_to='news/thumbnails/', verbose_name='Ảnh thumbnail')),
                ('meta_title', models.CharField(blank=True, help_text='Tiêu đề hiển thị trên Google (tối đa 70 ký tự)', max_length=70, verbose_name='SEO Title')),
                ('meta_description', models.CharField(blank=True, help_text='Mô tả hiển thị trên Google (tối đa 160 ký tự)', max_length=160, verbose_name='SEO Description')),
                ('meta_keywords', models.CharField(blank=True, help_text='Từ khóa SEO, cách nhau bởi dấu phẩy', max_length=255, verbose_name='Keywords')),
                ('canonical_url', models.URLField(blank=True, help_text='URL chính thức (để tránh duplicate content)', verbose_name='Canonical URL')),
                ('og_title', models.CharField(blank=True, help_text='Tiêu đề khi share Facebook/Twitter', max_length=95, verbose_name='OG Title')),
                ('og_description', models.CharField(blank=True, max_length=200, verbose_name='OG Description')),
                ('og_image', models.ImageField(blank=True, help_text='Ảnh khi share (1200x630 px)', upload_to='news/og/', verbose_name='OG Image')),
                ('is_published', models.BooleanField(default=False, verbose_name='Đã xuất bản')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Nổi bật')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xuất bản')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Lượt xem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_articles', to=settings.AUTH_USER_MODEL, verbose_name='Tác giả')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='news.category', verbose_name='Danh mục')),
            ],
            options={
                'verbose_name': 'Bài viết',
                'verbose_name_plural': 'Bài viết',
                'ordering': ['-is_featured', '-published_at', '-created_at'],
            },
        ),
    ]
