# Generated by Django 4.2.27 on 2026-02-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_article_cover_image_srcset'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.CharField(blank=True, help_text='Các tag cách nhau bởi dấu phẩy (VD: kinh nghiệm, du học Đức, TestDaF)', max_length=500, verbose_name='Tags'),
        ),
    ]
