# Generated by Django 4.2.27 on 2026-02-28 14:18

from django.db import migrations


# Ánh xạ slug → tên tiếng Việt có dấu
SLUG_TO_NAME = {
    'doi-song-duc': 'Đời sống Đức',
    'du-hoc-duc': 'Du học Đức',
    'kinh-nghiem': 'Kinh nghiệm',
    'tin-tuc-chung': 'Tin tức chung',
    'hoc-tieng-duc': 'Học tiếng Đức',
    'hoc-tieng-anh': 'Học tiếng Anh',
    'du-hoc': 'Du học',
    'thi-cu': 'Thi cử',
    'su-kien': 'Sự kiện',
}


def fix_category_names(apps, schema_editor):
    """Fix category names that were stored as slugs (no diacritics)."""
    Category = apps.get_model('news', 'Category')
    for cat in Category.objects.all():
        # If name equals slug, it was stored without diacritics
        if cat.name == cat.slug or '-' in cat.name:
            correct_name = SLUG_TO_NAME.get(cat.slug)
            if correct_name and cat.name != correct_name:
                cat.name = correct_name
                cat.save(update_fields=['name'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_add_tags_field'),
    ]

    operations = [
        migrations.RunPython(fix_category_names, noop),
    ]
