# Generated by Django 4.2.27 on 2026-01-29 06:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mediastream.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('icon', models.CharField(blank=True, default='folder', max_length=50, verbose_name='Icon')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='mediastream.mediacategory', verbose_name='Danh mục cha')),
            ],
            options={
                'verbose_name': 'Danh mục Media',
                'verbose_name_plural': 'Danh mục Media',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MediaPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tên playlist')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='stream/playlists/', verbose_name='Ảnh bìa')),
                ('language', models.CharField(choices=[('vi', 'Tiếng Việt'), ('en', 'Tiếng Anh'), ('de', 'Tiếng Đức'), ('all', 'Đa ngôn ngữ')], default='all', max_length=10, verbose_name='Ngôn ngữ')),
                ('level', models.CharField(choices=[('A1', 'A1 - Sơ cấp'), ('A2', 'A2 - Cơ bản'), ('B1', 'B1 - Trung cấp'), ('B2', 'B2 - Trung cao'), ('C1', 'C1 - Cao cấp'), ('C2', 'C2 - Thành thạo'), ('all', 'Tất cả trình độ')], default='all', max_length=10, verbose_name='Trình độ')),
                ('is_public', models.BooleanField(default=True, verbose_name='Công khai')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Nổi bật')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_playlists', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Playlist',
                'verbose_name_plural': 'Playlists',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='StreamMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('media_type', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio')], max_length=10, verbose_name='Loại media')),
                ('file', models.FileField(upload_to=mediastream.models.get_media_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogg', 'mov', 'flv', 'avi', 'm4v', 'mp3', 'wav', 'm4a', 'aac', 'flac', 'wma'])], verbose_name='File media')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Kích thước (bytes)')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Thời lượng (giây)')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME type')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Chiều rộng')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Chiều cao')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='stream/thumbnails/', verbose_name='Ảnh thumbnail')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('transcript', models.TextField(blank=True, verbose_name='Lời thoại/Transcript')),
                ('language', models.CharField(choices=[('vi', 'Tiếng Việt'), ('en', 'Tiếng Anh'), ('de', 'Tiếng Đức'), ('all', 'Đa ngôn ngữ')], default='all', max_length=10, verbose_name='Ngôn ngữ')),
                ('level', models.CharField(choices=[('A1', 'A1 - Sơ cấp'), ('A2', 'A2 - Cơ bản'), ('B1', 'B1 - Trung cấp'), ('B2', 'B2 - Trung cao'), ('C1', 'C1 - Cao cấp'), ('C2', 'C2 - Thành thạo'), ('all', 'Tất cả trình độ')], default='all', max_length=10, verbose_name='Trình độ')),
                ('tags', models.CharField(blank=True, help_text='Các tag cách nhau bởi dấu phẩy', max_length=500, verbose_name='Tags')),
                ('is_public', models.BooleanField(default=True, verbose_name='Công khai')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('requires_login', models.BooleanField(default=False, verbose_name='Yêu cầu đăng nhập')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Lượt xem')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Lượt tải')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_files', to='mediastream.mediacategory', verbose_name='Danh mục')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media', to=settings.AUTH_USER_MODEL, verbose_name='Người upload')),
            ],
            options={
                'verbose_name': 'Media Stream',
                'verbose_name_plural': 'Media Streams',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediastream.streammedia')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediastream.mediaplaylist')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MediaSubtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('vi', 'Tiếng Việt'), ('en', 'Tiếng Anh'), ('de', 'Tiếng Đức')], max_length=10, verbose_name='Ngôn ngữ')),
                ('label', models.CharField(blank=True, max_length=100, verbose_name='Nhãn hiển thị')),
                ('file', models.FileField(upload_to='stream/subtitles/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['vtt', 'srt'])], verbose_name='File phụ đề')),
                ('is_default', models.BooleanField(default=False, verbose_name='Mặc định')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='mediastream.streammedia', verbose_name='Media')),
            ],
            options={
                'verbose_name': 'Phụ đề',
                'verbose_name_plural': 'Phụ đề',
                'ordering': ['language'],
            },
        ),
        migrations.AddField(
            model_name='mediaplaylist',
            name='media_items',
            field=models.ManyToManyField(related_name='playlists', through='mediastream.PlaylistItem', to='mediastream.streammedia', verbose_name='Media'),
        ),
        migrations.AddIndex(
            model_name='streammedia',
            index=models.Index(fields=['uid'], name='mediastream_uid_1f96b2_idx'),
        ),
        migrations.AddIndex(
            model_name='streammedia',
            index=models.Index(fields=['slug'], name='mediastream_slug_c5ce69_idx'),
        ),
        migrations.AddIndex(
            model_name='streammedia',
            index=models.Index(fields=['media_type', 'language', 'level'], name='mediastream_media_t_8245e3_idx'),
        ),
        migrations.AddIndex(
            model_name='streammedia',
            index=models.Index(fields=['is_active', 'is_public'], name='mediastream_is_acti_16bae0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='playlistitem',
            unique_together={('playlist', 'media')},
        ),
        migrations.AlterUniqueTogether(
            name='mediasubtitle',
            unique_together={('media', 'language')},
        ),
    ]
