# Generated by Django 4.2.27 on 2026-02-22 09:10

import django.core.validators
from django.db import migrations, models
import mediastream.models


class Migration(migrations.Migration):

    dependencies = [
        ('mediastream', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streammedia',
            name='file',
            field=models.FileField(storage=mediastream.models.get_media_storage, upload_to=mediastream.models.get_media_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogg', 'mov', 'flv', 'avi', 'm4v', 'mp3', 'wav', 'm4a', 'aac', 'flac', 'wma'])], verbose_name='File media'),
        ),
        migrations.AlterField(
            model_name='streammedia',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, storage=mediastream.models.get_thumbnail_storage, upload_to='stream/thumbnails/', verbose_name='Ảnh thumbnail'),
        ),
    ]
