# Generated by Django 4.2.27 on 2026-03-28 10:49

import django.core.validators
from django.db import migrations, models
import mediastream.models


class Migration(migrations.Migration):

    dependencies = [
        ('mediastream', '0003_add_gdrive_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streammedia',
            name='file',
            field=models.FileField(blank=True, storage=mediastream.models.get_media_storage, upload_to=mediastream.models.get_media_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogg', 'mov', 'flv', 'avi', 'm4v', 'mp3', 'wav', 'm4a', 'aac', 'flac', 'wma'])], verbose_name='File media'),
        ),
        migrations.AlterField(
            model_name='streammedia',
            name='media_type',
            field=models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('podcast', 'Podcast')], max_length=10, verbose_name='Loại media'),
        ),
    ]
