# Generated by Django 4.2.27 on 2026-04-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediastream', '0004_add_podcast_media_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GDriveAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Gmail')),
                ('refresh_token', models.TextField(help_text='🔒 OAuth2 refresh token — mã hoá khi lưu.', verbose_name='Refresh Token')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('storage_used', models.BigIntegerField(default=0, verbose_name='Đã dùng (bytes)')),
                ('storage_total', models.BigIntegerField(default=16106127360, verbose_name='Tổng (bytes)')),
                ('root_folder_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Thư mục gốc ID')),
                ('folder_mapping', models.JSONField(blank=True, default=dict, help_text='{"video": "FOLDER_ID", "audio": "FOLDER_ID", "podcast": "FOLDER_ID"}', verbose_name='Thư mục theo loại media')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày thêm')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='Sử dụng lần cuối')),
                ('last_storage_check', models.DateTimeField(blank=True, null=True, verbose_name='Kiểm tra storage lần cuối')),
            ],
            options={
                'verbose_name': 'Tài khoản GDrive',
                'verbose_name_plural': 'Tài khoản GDrive',
                'ordering': ['-is_active', 'storage_used'],
            },
        ),
    ]
