# Generated by Django 4.2.27 on 2026-04-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediastream', '0005_gdriveaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='streammedia',
            name='youtube_id',
            field=models.CharField(blank=True, default='', help_text='YouTube video ID hoặc URL (tự động trích xuất ID và thumbnail)', max_length=100, verbose_name='YouTube Video ID'),
        ),
        migrations.AlterField(
            model_name='streammedia',
            name='storage_type',
            field=models.CharField(choices=[('local', 'Local Storage'), ('gdrive', 'Google Drive'), ('youtube', 'YouTube')], default='local', help_text='local = file trên VPS, gdrive = stream từ Google Drive', max_length=10, verbose_name='Loại lưu trữ'),
        ),
    ]
