# Generated by Django 4.2.27 on 2025-12-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('youtube_id', models.CharField(help_text='ID của video YouTube (phần sau v= trong URL)', max_length=20, verbose_name='YouTube Video ID')),
                ('thumbnail', models.URLField(blank=True, help_text='Để trống sẽ tự lấy từ YouTube', verbose_name='Ảnh thumbnail')),
                ('duration', models.CharField(blank=True, help_text='Ví dụ: 12:30', max_length=10, verbose_name='Thời lượng')),
                ('language', models.CharField(choices=[('en', 'Tiếng Anh'), ('de', 'Tiếng Đức'), ('vi', 'Tiếng Việt'), ('ja', 'Tiếng Nhật'), ('ko', 'Tiếng Hàn'), ('fr', 'Tiếng Pháp'), ('zh', 'Tiếng Trung')], default='en', max_length=5, verbose_name='Ngôn ngữ')),
                ('level', models.CharField(choices=[('A1', 'A1 - Sơ cấp'), ('A2', 'A2 - Sơ trung'), ('B1', 'B1 - Trung cấp'), ('B2', 'B2 - Trung cao'), ('C1', 'C1 - Cao cấp'), ('C2', 'C2 - Thành thạo'), ('all', 'Mọi trình độ')], default='all', max_length=5, verbose_name='Trình độ')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Lượt xem')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Nổi bật')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['-is_featured', 'order', '-created_at'],
            },
        ),
    ]
