# Generated by Django 4.2.27 on 2025-12-11 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='youtube_id',
            field=models.CharField(help_text='Nhập ID video (ví dụ: dQw4w9WgXcQ) hoặc URL đầy đủ từ YouTube', max_length=100, verbose_name='YouTube Video ID hoặc URL'),
        ),
    ]
