# Generated by Django 4.2.27 on 2025-12-11 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_video_youtube_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'Deutsch'), ('all', 'Mọi ngôn ngữ')], default='en', max_length=5, verbose_name='Ngôn ngữ'),
        ),
    ]
