# Generated by Django 4.2.17 on 2026-01-24 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_video_bookmarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên hiển thị')),
                ('url', models.CharField(help_text='URL nội bộ (VD: /about) hoặc URL bên ngoài (VD: https://facebook.com)', max_length=500, verbose_name='URL')),
                ('icon', models.CharField(blank=True, help_text='Tên icon (VD: FaHome, FaFacebook, MdEmail)', max_length=50, verbose_name='Icon')),
                ('location', models.CharField(choices=[('navbar', 'Navbar'), ('footer', 'Footer'), ('both', 'Cả hai')], default='navbar', max_length=10, verbose_name='Vị trí')),
                ('footer_section', models.CharField(blank=True, choices=[('company', 'Công ty'), ('resources', 'Tài nguyên'), ('community', 'Cộng đồng'), ('legal', 'Pháp lý'), ('social', 'Mạng xã hội')], help_text='Chỉ áp dụng khi location là Footer hoặc Cả hai', max_length=20, verbose_name='Phần trong Footer')),
                ('open_in_new_tab', models.BooleanField(default=False, help_text='Thường dùng cho link bên ngoài', verbose_name='Mở tab mới')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Để trống nếu là menu chính', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.navigationlink', verbose_name='Menu cha')),
            ],
            options={
                'verbose_name': 'Link điều hướng',
                'verbose_name_plural': 'Links điều hướng',
                'ordering': ['location', 'footer_section', 'order', 'name'],
            },
        ),
    ]
