# Generated by Django 4.2.27 on 2026-01-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_navigation_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên định danh (VD: n8n_api_key, admin_secret)', max_length=100, unique=True, verbose_name='Tên key')),
                ('key', models.CharField(help_text='Giá trị key (tự động tạo nếu để trống)', max_length=255, verbose_name='API Key')),
                ('key_type', models.CharField(choices=[('n8n_api', 'N8N Automation API Key'), ('admin_secret', 'Admin Secret Key'), ('webhook', 'Webhook Secret'), ('external_api', 'External API Key'), ('other', 'Other')], default='other', max_length=20, verbose_name='Loại key')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Sử dụng lần cuối')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='Số lần sử dụng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['key_type', 'name'],
            },
        ),
    ]
