# Generated by Django 4.2.27 on 2026-01-25 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_add_apikey_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='ai_model',
            field=models.CharField(blank=True, help_text='Model AI đã sử dụng (GPT-4, Claude, etc.)', max_length=50, verbose_name='AI Model'),
        ),
        migrations.AddField(
            model_name='video',
            name='human_reviewed',
            field=models.BooleanField(default=False, help_text='Con người đã review nội dung', verbose_name='Đã review'),
        ),
        migrations.AddField(
            model_name='video',
            name='is_ai_generated',
            field=models.BooleanField(default=False, help_text='Nội dung được tạo bởi AI', verbose_name='AI tạo nội dung'),
        ),
        migrations.AddField(
            model_name='video',
            name='n8n_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='N8N tạo lúc'),
        ),
        migrations.AddField(
            model_name='video',
            name='n8n_execution_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='N8N Execution ID'),
        ),
        migrations.AddField(
            model_name='video',
            name='n8n_workflow_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='N8N Workflow ID'),
        ),
        migrations.AddField(
            model_name='video',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Review lúc'),
        ),
        migrations.AddField(
            model_name='video',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='Người review'),
        ),
        migrations.AddField(
            model_name='video',
            name='source',
            field=models.CharField(choices=[('manual', 'Tạo thủ công'), ('n8n', 'N8N Automation'), ('api', 'API Import'), ('rss', 'RSS Feed'), ('scraper', 'Web Scraper')], default='manual', help_text='Bài viết được tạo từ nguồn nào', max_length=20, verbose_name='Nguồn tạo'),
        ),
        migrations.AddField(
            model_name='video',
            name='source_id',
            field=models.CharField(blank=True, help_text='ID từ hệ thống nguồn (để tránh duplicate)', max_length=100, verbose_name='ID nguồn'),
        ),
        migrations.AddField(
            model_name='video',
            name='source_url',
            field=models.URLField(blank=True, help_text='Link bài viết gốc (nếu import)', verbose_name='URL nguồn'),
        ),
    ]
