# Generated by Django 4.2.27 on 2026-01-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_video_ai_model_video_human_reviewed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên định danh (VD: postgres_password, smtp_password)', max_length=100, unique=True, verbose_name='Tên cài đặt')),
                ('value', models.TextField(help_text='Giá trị cài đặt (có thể là password)', verbose_name='Giá trị')),
                ('setting_type', models.CharField(choices=[('database', 'Database Config'), ('email', 'Email Config'), ('api', 'API Config'), ('security', 'Security'), ('general', 'General')], default='general', max_length=20, verbose_name='Loại')),
                ('is_secret', models.BooleanField(default=False, help_text='Đánh dấu nếu là password để ẩn khi hiển thị', verbose_name='Là mật khẩu/secret')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
                'ordering': ['setting_type', 'name'],
            },
        ),
    ]
