# Generated by Django 4.2.27 on 2026-02-14 10:17

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='UnstressVN', max_length=100, verbose_name='Tên website')),
                ('site_description', models.TextField(blank=True, default='Nền tảng học ngoại ngữ miễn phí', verbose_name='Mô tả website')),
                ('contact_email', models.EmailField(default='unstressvn@gmail.com', max_length=254, verbose_name='Email liên hệ')),
                ('debug_mode', models.BooleanField(default=True, help_text='⚠️ BẮT BUỘC tắt khi deploy production!', verbose_name='Chế độ Debug')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Bật khi đang bảo trì website — hiển thị trang bảo trì.', verbose_name='Chế độ bảo trì')),
                ('allowed_hosts', models.TextField(default='localhost,127.0.0.1,host.docker.internal', help_text='Danh sách domain được phép truy cập, phân cách bằng dấu phẩy. VD: unstressvn.com,www.unstressvn.com', verbose_name='Allowed Hosts')),
                ('csrf_trusted_origins', models.TextField(default='http://localhost:8000,http://127.0.0.1:8000,http://host.docker.internal:8000', help_text='URL gốc tin cậy cho CSRF, phân cách bằng dấu phẩy. VD: https://unstressvn.com,https://www.unstressvn.com', verbose_name='CSRF Trusted Origins')),
                ('cors_allowed_origins', models.TextField(default='http://localhost:3000,http://127.0.0.1:3000,http://localhost:5173,http://127.0.0.1:5173,http://localhost:8000', help_text='Origin frontend được phép CORS, phân cách bằng dấu phẩy.', verbose_name='CORS Allowed Origins')),
                ('email_host', models.CharField(default='smtp.gmail.com', max_length=255, verbose_name='SMTP Host')),
                ('email_port', models.IntegerField(default=587, verbose_name='SMTP Port')),
                ('email_use_tls', models.BooleanField(default=True, verbose_name='Sử dụng TLS')),
                ('email_host_user', models.CharField(blank=True, default='', max_length=255, verbose_name='Email tài khoản SMTP')),
                ('email_host_password', core.fields.EncryptedTextField(blank=True, default='', help_text='🔒 App Password (Gmail) hoặc SMTP password. Mã hoá tự động khi lưu.', verbose_name='Mật khẩu SMTP')),
                ('default_from_email', models.CharField(default='UnstressVN <unstressvn@gmail.com>', max_length=255, verbose_name='Email người gửi')),
                ('youtube_api_key', core.fields.EncryptedTextField(blank=True, default='', help_text='🔒 Google YouTube Data API v3 key. Mã hoá tự động khi lưu.', verbose_name='YouTube API Key')),
                ('minio_endpoint_url', models.CharField(blank=True, default='', help_text='VD: https://minio.unstressvn.com — Để trống = local storage.', max_length=500, verbose_name='MinIO Endpoint URL')),
                ('minio_access_key', core.fields.EncryptedTextField(blank=True, default='', help_text='🔒 Mã hoá tự động khi lưu.', verbose_name='MinIO Access Key')),
                ('minio_secret_key', core.fields.EncryptedTextField(blank=True, default='', help_text='🔒 Mã hoá tự động khi lưu.', verbose_name='MinIO Secret Key')),
                ('minio_media_bucket', models.CharField(default='mediastream', max_length=100, verbose_name='MinIO Bucket')),
                ('minio_region', models.CharField(default='us-east-1', max_length=50, verbose_name='MinIO Region')),
                ('minio_custom_domain', models.CharField(blank=True, default='', max_length=500, verbose_name='MinIO Custom Domain (CDN)')),
                ('elasticsearch_url', models.CharField(default='http://localhost:9200', max_length=500, verbose_name='Elasticsearch URL')),
                ('elasticsearch_autosync', models.BooleanField(default=False, verbose_name='Elasticsearch Auto-sync')),
                ('redis_url', models.CharField(blank=True, default='', help_text='VD: redis://localhost:6379 — Để trống = InMemory channel layer.', max_length=500, verbose_name='Redis URL')),
                ('facebook_url', models.URLField(blank=True, default='', verbose_name='Facebook')),
                ('youtube_channel_url', models.URLField(blank=True, default='', verbose_name='YouTube Channel')),
                ('tiktok_url', models.URLField(blank=True, default='', verbose_name='TikTok')),
                ('github_url', models.URLField(blank=True, default='', verbose_name='GitHub')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
            ],
            options={
                'verbose_name': 'Cấu hình hệ thống',
                'verbose_name_plural': 'Cấu hình hệ thống',
            },
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='setting_type',
            field=models.CharField(choices=[('database', 'Database Config'), ('email', 'Email Config'), ('storage', 'Storage (MinIO/S3)'), ('api', 'API Config'), ('security', 'Security'), ('general', 'General')], default='general', max_length=20, verbose_name='Loại'),
        ),
    ]
