# Generated by Django 4.2.27 on 2026-02-22 15:29

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_siteconfiguration_alter_sitesettings_setting_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='gemini_api_key',
            field=core.fields.EncryptedTextField(blank=True, default='', help_text='🔒 Google Gemini API key cho dịch phụ đề realtime. Mã hoá tự động khi lưu.', verbose_name='Google Gemini API Key'),
        ),
    ]
