# Generated by Django 4.2.27 on 2026-02-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_gemini_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='allowed_ips',
            field=models.TextField(blank=True, default='', help_text='Comma-separated IPs (empty = allow all)', verbose_name='Allowed IPs'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Key hết hạn tự động (blank = không hết hạn)', null=True, verbose_name='Hết hạn'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='key_hash',
            field=models.CharField(blank=True, default='', help_text='HMAC-SHA256 hash — auto-generated on save', max_length=128, verbose_name='Key Hash'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='key_prefix',
            field=models.CharField(blank=True, default='', help_text='First 8 chars for identification', max_length=12, verbose_name='Key Prefix'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='last_used_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP lần cuối'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='rate_limit',
            field=models.PositiveIntegerField(default=0, help_text='0 = unlimited', verbose_name='Rate limit/min'),
        ),
    ]
