# Generated by Django 4.2.27 on 2026-02-28 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_apikey_security_upgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationlink',
            name='badge_text',
            field=models.CharField(blank=True, help_text='Text hiển thị trên badge (VD: New, Hot, Soon). Để trống = không badge', max_length=20, verbose_name='Badge'),
        ),
        migrations.AddField(
            model_name='navigationlink',
            name='is_coming_soon',
            field=models.BooleanField(default=False, help_text='Hiển thị badge "Soon" và vô hiệu hoá link', verbose_name='Sắp ra mắt'),
        ),
        migrations.AddField(
            model_name='navigationlink',
            name='name_de',
            field=models.CharField(blank=True, help_text='Tên hiển thị bằng tiếng Đức (fallback = name)', max_length=100, verbose_name='Tên tiếng Đức'),
        ),
        migrations.AddField(
            model_name='navigationlink',
            name='name_en',
            field=models.CharField(blank=True, help_text='Tên hiển thị bằng tiếng Anh (fallback = name)', max_length=100, verbose_name='Tên tiếng Anh'),
        ),
        migrations.AddField(
            model_name='navigationlink',
            name='name_vi',
            field=models.CharField(blank=True, help_text='Tên hiển thị bằng tiếng Việt (fallback = name)', max_length=100, verbose_name='Tên tiếng Việt'),
        ),
        migrations.AlterField(
            model_name='navigationlink',
            name='icon',
            field=models.CharField(blank=True, help_text='Tên lucide icon (VD: Newspaper, BookOpen, Wrench, Users, GraduationCap)', max_length=50, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='navigationlink',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Để trống nếu là menu chính / dropdown', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.navigationlink', verbose_name='Menu cha'),
        ),
        migrations.AlterField(
            model_name='navigationlink',
            name='url',
            field=models.CharField(help_text='URL nội bộ (VD: /tin-tuc) hoặc URL bên ngoài (VD: https://discord.gg/...)', max_length=500, verbose_name='URL'),
        ),
    ]
