# Generated by Django 4.2.27 on 2026-03-28 07:31

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_navigation_link_enhancements'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='gdrive_folder_id',
            field=models.CharField(blank=True, default='', help_text='ID thư mục mặc định trên Google Drive để upload video. Lấy từ URL: drive.google.com/drive/folders/FOLDER_ID', max_length=255, verbose_name='Google Drive Folder ID'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='gdrive_service_account_json',
            field=core.fields.EncryptedTextField(blank=True, default='', help_text='🔒 Nội dung file JSON Service Account (Google Cloud). Mã hoá tự động khi lưu.', verbose_name='Google Drive Service Account JSON'),
        ),
    ]
