# Generated by Django 4.2.27 on 2026-03-28 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_gdrive_service_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteSettings',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='elasticsearch_autosync',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='elasticsearch_url',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='minio_access_key',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='minio_custom_domain',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='minio_endpoint_url',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='minio_media_bucket',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='minio_region',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='minio_secret_key',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='redis_url',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='tiktok_url',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='youtube_channel_url',
        ),
    ]
