# Generated by Django 4.2.27 on 2026-03-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_dead_fields_minio_elasticsearch_redis_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationlink',
            name='description',
            field=models.CharField(blank=True, help_text='Mô tả hiển thị dưới tên menu (tuỳ chọn, dùng cho mega-menu)', max_length=200, verbose_name='Mô tả ngắn'),
        ),
    ]
