# Generated by Django 4.2.27 on 2026-03-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_description_to_navigationlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='gdrive_folder_mapping',
            field=models.JSONField(blank=True, default=dict, help_text='Tự động quản lý: {"video": "FOLDER_ID", "audio": "FOLDER_ID", "podcast": "FOLDER_ID"}', verbose_name='Thư mục GDrive theo loại media'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='gdrive_folder_id',
            field=models.CharField(blank=True, default='', help_text='ID thư mục gốc trên Google Drive. Lấy từ URL: drive.google.com/drive/folders/FOLDER_ID', max_length=255, verbose_name='Google Drive Folder ID'),
        ),
    ]
