# Generated by Django 4.2.27 on 2026-04-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_gdrive_folder_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='direct_upload_domain',
            field=models.CharField(blank=True, default='', help_text='Subdomain upload trực tiếp VPS (bypass Cloudflare 100MB limit). VD: upload.unstressvn.com — Cần cấu hình DNS-only (grey cloud) trên Cloudflare.', max_length=255, verbose_name='Direct Upload Domain'),
        ),
    ]
