# Generated by Django 4.2.27 on 2026-04-04 14:15

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_direct_upload_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='gdrive_oauth_client_id',
            field=models.CharField(blank=True, default='', help_text='Google Cloud Console → Credentials → OAuth 2.0 Client ID (Web application)', max_length=255, verbose_name='OAuth2 Client ID'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='gdrive_oauth_client_secret',
            field=core.fields.EncryptedTextField(blank=True, default='', help_text='🔒 Client Secret từ Google Cloud Console. Mã hoá tự động.', verbose_name='OAuth2 Client Secret'),
        ),
    ]
