# Generated by Django 4.2.27 on 2026-04-04 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_siteconfiguration_gdrive_oauth_client_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='gdrive_folder_id',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='gdrive_folder_mapping',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='gdrive_service_account_json',
        ),
    ]
