# Generated by Django 4.2.27 on 2026-01-24 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filemanager.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên')),
                ('logo_type', models.CharField(choices=[('favicon', 'Favicon (16x16, 32x32)'), ('icon-small', 'Icon nhỏ (< 100px, SVG)'), ('icon-medium', 'Icon vừa (100-200px, WebP)'), ('logo-header', 'Logo Header (WebP)'), ('logo-footer', 'Logo Footer (WebP)'), ('logo-full', 'Logo đầy đủ (WebP)'), ('og-image', 'OG Image (1200x630, WebP)')], max_length=20, unique=True, verbose_name='Loại logo')),
                ('svg_code', models.TextField(blank=True, help_text='Code SVG cho logo nhỏ < 100px', verbose_name='SVG Code')),
                ('image', models.ImageField(blank=True, help_text='File ảnh WebP cho logo lớn >= 100px', upload_to='logos/', verbose_name='Image file')),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Logo',
                'verbose_name_plural': 'Site Logos',
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên file')),
                ('file', models.FileField(upload_to=filemanager.models.upload_media_path, verbose_name='File')),
                ('folder', models.CharField(choices=[('images', 'Hình ảnh'), ('documents', 'Tài liệu'), ('avatars', 'Avatar'), ('covers', 'Ảnh bìa'), ('logos', 'Logo'), ('resources', 'Tài nguyên'), ('other', 'Khác')], default='images', max_length=50, verbose_name='Thư mục')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Kích thước (bytes)')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='Loại file')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Chiều rộng')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Chiều cao')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Alt text (SEO)')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Media File',
                'verbose_name_plural': 'Media Files',
                'ordering': ['-created_at'],
            },
        ),
    ]
