# Generated by Django 4.2.27 on 2025-12-09 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Ảnh đại diện')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Giới thiệu')),
                ('target_language', models.CharField(choices=[('english', 'Tiếng Anh'), ('german', 'Tiếng Đức')], default='english', max_length=20, verbose_name='Ngôn ngữ mục tiêu')),
                ('level', models.CharField(choices=[('A1', 'A1 - Sơ cấp'), ('A2', 'A2 - Sơ cấp'), ('B1', 'B1 - Trung cấp'), ('B2', 'B2 - Trung cấp'), ('C1', 'C1 - Cao cấp'), ('C2', 'C2 - Cao cấp')], default='A1', max_length=2, verbose_name='Trình độ')),
                ('skill_focus', models.CharField(choices=[('speaking', 'Nói'), ('listening', 'Nghe'), ('reading', 'Đọc'), ('writing', 'Viết'), ('all', 'Tất cả')], default='all', max_length=20, verbose_name='Kỹ năng tập trung')),
                ('is_public', models.BooleanField(default=True, verbose_name='Hiển thị công khai')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Hồ sơ người dùng',
                'verbose_name_plural': 'Hồ sơ người dùng',
            },
        ),
    ]
