# Generated by Django 4.2.27 on 2025-12-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allow_messages',
            field=models.BooleanField(default=True, verbose_name='Cho phép nhắn tin'),
        ),
    ]
