# Generated by Django 4.2.27 on 2026-01-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='skill_focus',
            field=models.CharField(choices=[('speaking', 'Nói'), ('listening', 'Nghe'), ('reading', 'Đọc'), ('writing', 'Viết'), ('grammar', 'Ngữ pháp'), ('vocabulary', 'Từ vựng'), ('all', 'Tất cả')], default='all', max_length=20, verbose_name='Kỹ năng tập trung'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='target_language',
            field=models.CharField(blank=True, choices=[('en', 'Tiếng Anh'), ('de', 'Tiếng Đức')], default='en', max_length=20, verbose_name='Ngôn ngữ mục tiêu'),
        ),
    ]
