#!/usr/bin/env python
"""
Script tạo và quản lý password bảo mật cao cho UnstressVN
Usage:
    python scripts/manage_passwords.py generate           # Tạo password mới
    python scripts/manage_passwords.py init               # Khởi tạo default settings
    python scripts/manage_passwords.py show               # Hiển thị settings (ẩn secret)
    python scripts/manage_passwords.py export             # Export settings ra file .env.example
    python scripts/manage_passwords.py update-postgres    # Cập nhật password PostgreSQL
"""

import os
import sys
import string
import random
import argparse

# Setup Django
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'unstressvn_settings.settings')

import django
django.setup()

from core.models import SiteSettings, APIKey


def generate_secure_password(length=32, include_special=True):
    """Tạo password bảo mật cao"""
    if length < 16:
        length = 16
    
    lowercase = string.ascii_lowercase
    uppercase = string.ascii_uppercase
    digits = string.digits
    special = '!@#$%^&*()_+-=[]{}|;:,.<>?' if include_special else ''
    
    # Ensure at least one of each type
    password = [
        random.choice(lowercase),
        random.choice(uppercase),
        random.choice(digits),
    ]
    
    if include_special:
        password.append(random.choice(special))
    
    # Fill the rest
    all_chars = lowercase + uppercase + digits + special
    remaining = length - len(password)
    password.extend(random.choice(all_chars) for _ in range(remaining))
    
    random.shuffle(password)
    return ''.join(password)


def cmd_generate(args):
    """Tạo password mới"""
    print("\n🔐 Password Generator - UnstressVN")
    print("=" * 50)
    
    count = args.count or 5
    length = args.length or 32
    
    print(f"\nTạo {count} password với độ dài {length} ký tự:\n")
    
    for i in range(count):
        password = generate_secure_password(length, not args.no_special)
        print(f"  {i+1}. {password}")
    
    print("\n💡 Copy password và lưu an toàn!")
    print()


def cmd_init(args):
    """Khởi tạo default settings"""
    print("\n⚙️ Khởi tạo Site Settings")
    print("=" * 50)
    
    # Init site settings
    SiteSettings.init_default_settings()
    print("✅ Đã khởi tạo Site Settings")
    
    # Init API keys
    created = APIKey.create_default_keys()
    if created:
        print(f"✅ Đã tạo API Keys: {', '.join(created)}")
    else:
        print("ℹ️ API Keys đã tồn tại")
    
    print("\n📋 Settings hiện tại:")
    for setting in SiteSettings.objects.all():
        value = "●●●●●●●●" if setting.is_secret else setting.value
        print(f"  • {setting.name}: {value}")
    
    print()


def cmd_show(args):
    """Hiển thị tất cả settings"""
    print("\n📋 Site Settings - UnstressVN")
    print("=" * 50)
    
    # Group by type
    for setting_type, type_name in SiteSettings.SETTING_TYPE_CHOICES:
        settings = SiteSettings.objects.filter(setting_type=setting_type)
        if settings.exists():
            print(f"\n🔹 {type_name}:")
            for s in settings:
                if s.is_secret and not args.show_secrets:
                    value = "●●●●●●●●"
                else:
                    value = s.value
                print(f"   {s.name}: {value}")
    
    print("\n🔹 API Keys:")
    for key in APIKey.objects.filter(is_active=True):
        if args.show_secrets:
            print(f"   {key.name}: {key.key}")
        else:
            print(f"   {key.name}: {key.key[:10]}...{key.key[-4:]}")
    
    if not args.show_secrets:
        print("\n💡 Thêm --show-secrets để hiển thị password đầy đủ")
    print()


def cmd_export(args):
    """Export settings ra file .env.example"""
    print("\n📤 Export Settings to .env")
    print("=" * 50)
    
    output_file = args.output or '.env.generated'
    
    lines = [
        "# UnstressVN Environment Variables",
        "# Generated by manage_passwords.py",
        f"# Date: {__import__('datetime').datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "",
        "# ============ Database ============",
    ]
    
    # Database settings
    db_settings = SiteSettings.objects.filter(setting_type='database')
    for s in db_settings:
        env_name = s.name.upper()
        lines.append(f"{env_name}={s.value}")
    
    lines.append("")
    lines.append("# ============ API Keys ============")
    
    for key in APIKey.objects.filter(is_active=True):
        env_name = key.name.upper()
        lines.append(f"{env_name}={key.key}")
    
    lines.append("")
    lines.append("# ============ Email ============")
    
    email_settings = SiteSettings.objects.filter(setting_type='email')
    for s in email_settings:
        env_name = s.name.upper()
        lines.append(f"{env_name}={s.value}")
    
    # Write to file
    with open(output_file, 'w') as f:
        f.write('\n'.join(lines))
    
    print(f"✅ Đã export ra: {output_file}")
    print(f"⚠️ Lưu ý: File này chứa password thật, bảo mật cẩn thận!")
    print()


def cmd_update_postgres(args):
    """Cập nhật password PostgreSQL mới"""
    print("\n🐘 Update PostgreSQL Password")
    print("=" * 50)
    
    new_password = generate_secure_password(32, include_special=False)  # No special for postgres
    
    print(f"\n🔐 Password mới (không có ký tự đặc biệt): ")
    print(f"   {new_password}")
    
    print("\n📋 Các bước cần thực hiện:")
    print("   1. Cập nhật password trong PostgreSQL:")
    print(f"      sudo -u postgres psql -c \"ALTER USER unstressvn WITH PASSWORD '{new_password}';\"")
    print()
    print("   2. Cập nhật file .env:")
    print(f"      DATABASE_PASSWORD={new_password}")
    print()
    print("   3. Restart server:")
    print("      ./stop.sh && ./start.sh")
    print()
    
    # Update in database if confirmed
    if args.apply:
        SiteSettings.set(
            name='postgres_password',
            value=new_password,
            setting_type='database',
            is_secret=True,
            description='PostgreSQL Password'
        )
        print("✅ Đã cập nhật password trong SiteSettings")
    else:
        print("💡 Thêm --apply để lưu password vào database")
    print()


def main():
    parser = argparse.ArgumentParser(
        description='UnstressVN Password Manager',
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    
    subparsers = parser.add_subparsers(dest='command', help='Commands')
    
    # generate command
    gen_parser = subparsers.add_parser('generate', help='Tạo password mới')
    gen_parser.add_argument('-n', '--count', type=int, default=5, help='Số password tạo')
    gen_parser.add_argument('-l', '--length', type=int, default=32, help='Độ dài password')
    gen_parser.add_argument('--no-special', action='store_true', help='Không dùng ký tự đặc biệt')
    
    # init command
    subparsers.add_parser('init', help='Khởi tạo default settings')
    
    # show command
    show_parser = subparsers.add_parser('show', help='Hiển thị settings')
    show_parser.add_argument('--show-secrets', action='store_true', help='Hiển thị password đầy đủ')
    
    # export command
    export_parser = subparsers.add_parser('export', help='Export ra file .env')
    export_parser.add_argument('-o', '--output', help='Output file', default='.env.generated')
    
    # update-postgres command
    pg_parser = subparsers.add_parser('update-postgres', help='Tạo password PostgreSQL mới')
    pg_parser.add_argument('--apply', action='store_true', help='Lưu password vào database')
    
    args = parser.parse_args()
    
    if args.command == 'generate':
        cmd_generate(args)
    elif args.command == 'init':
        cmd_init(args)
    elif args.command == 'show':
        cmd_show(args)
    elif args.command == 'export':
        cmd_export(args)
    elif args.command == 'update-postgres':
        cmd_update_postgres(args)
    else:
        parser.print_help()


if __name__ == '__main__':
    main()
