# Generated by Django 4.2.27 on 2026-01-24 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('icon', models.CharField(blank=True, help_text='Tên icon (VD: FaBook, FaBrain)', max_length=50, verbose_name='Icon')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Danh mục công cụ',
                'verbose_name_plural': 'Danh mục công cụ',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên công cụ')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('tool_type', models.CharField(choices=[('internal', 'Công cụ nội bộ'), ('external', 'Link bên ngoài'), ('embed', 'Nhúng (iframe)')], default='internal', max_length=20, verbose_name='Loại công cụ')),
                ('url', models.CharField(blank=True, help_text='URL bên ngoài hoặc path component nội bộ', max_length=500, verbose_name='URL/Path')),
                ('embed_code', models.TextField(blank=True, help_text='HTML embed code (cho loại embed)', verbose_name='Embed code')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icon')),
                ('cover_image', models.ImageField(blank=True, upload_to='tools/covers/', verbose_name='Ảnh bìa')),
                ('language', models.CharField(choices=[('en', 'Tiếng Anh'), ('de', 'Tiếng Đức'), ('all', 'Tất cả')], default='all', max_length=5, verbose_name='Ngôn ngữ')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Nổi bật')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Lượt xem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools', to='tools.toolcategory', verbose_name='Danh mục')),
            ],
            options={
                'verbose_name': 'Công cụ học tập',
                'verbose_name_plural': 'Công cụ học tập',
                'ordering': ['-is_featured', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlashcardDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên bộ thẻ')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('language', models.CharField(choices=[('en', 'Tiếng Anh'), ('de', 'Tiếng Đức')], default='de', max_length=5, verbose_name='Ngôn ngữ')),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='A1', max_length=5, verbose_name='Trình độ')),
                ('is_public', models.BooleanField(default=True, verbose_name='Công khai')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Nổi bật')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flashcard_decks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bộ Flashcard',
                'verbose_name_plural': 'Bộ Flashcard',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.TextField(help_text='Từ vựng hoặc câu hỏi', verbose_name='Mặt trước')),
                ('back', models.TextField(help_text='Nghĩa hoặc câu trả lời', verbose_name='Mặt sau')),
                ('example', models.TextField(blank=True, verbose_name='Ví dụ')),
                ('pronunciation', models.CharField(blank=True, max_length=200, verbose_name='Phát âm')),
                ('audio_url', models.URLField(blank=True, verbose_name='Audio URL')),
                ('image', models.ImageField(blank=True, upload_to='flashcards/', verbose_name='Hình ảnh')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='tools.flashcarddeck', verbose_name='Bộ thẻ')),
            ],
            options={
                'verbose_name': 'Thẻ Flashcard',
                'verbose_name_plural': 'Thẻ Flashcard',
                'ordering': ['order', 'id'],
            },
        ),
    ]
