# Generated by Django 4.2.27 on 2026-01-30 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools', to=settings.AUTH_USER_MODEL, verbose_name='Tác giả'),
        ),
        migrations.AddField(
            model_name='tool',
            name='content',
            field=models.TextField(blank=True, help_text='HTML content cho bài viết hướng dẫn', verbose_name='Nội dung bài viết'),
        ),
        migrations.AddField(
            model_name='tool',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Đoạn mô tả ngắn hiển thị trong danh sách', verbose_name='Tóm tắt'),
        ),
        migrations.AddField(
            model_name='tool',
            name='featured_image',
            field=models.ImageField(blank=True, upload_to='tools/featured/', verbose_name='Ảnh đại diện'),
        ),
        migrations.AddField(
            model_name='tool',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Xuất bản'),
        ),
        migrations.AddField(
            model_name='tool',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='tool',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='tool',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày xuất bản'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='description',
            field=models.TextField(verbose_name='Mô tả ngắn'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='tool_type',
            field=models.CharField(choices=[('internal', 'Công cụ nội bộ'), ('external', 'Link bên ngoài'), ('embed', 'Nhúng (iframe)'), ('article', 'Bài viết hướng dẫn')], default='article', max_length=20, verbose_name='Loại công cụ'),
        ),
    ]
