# Generated by Django 4.2.27 on 2026-02-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_tool_author_tool_content_tool_excerpt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='cover_image_srcset',
            field=models.JSONField(blank=True, default=dict, help_text='Auto-generated responsive image URLs', verbose_name='Responsive images'),
        ),
    ]
