# Generated by Django 4.2.27 on 2025-12-09 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(unique=True, verbose_name='Đường dẫn')),
                ('icon', models.CharField(default='bi-translate', max_length=50, verbose_name='Icon (Bootstrap Icons)')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Danh mục',
                'verbose_name_plural': 'Danh mục',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Loại tài liệu')),
                ('slug', models.SlugField(unique=True, verbose_name='Đường dẫn')),
                ('icon', models.CharField(default='bi-file-earmark', max_length=50, verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Loại tài liệu',
                'verbose_name_plural': 'Loại tài liệu',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tên tài liệu')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Đường dẫn')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/', verbose_name='File tài liệu')),
                ('youtube_url', models.URLField(blank=True, null=True, verbose_name='Link YouTube')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Ảnh bìa')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='Tác giả')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Nổi bật')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Lượt xem')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Lượt tải')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='resources.category', verbose_name='Danh mục')),
                ('resource_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='resources.resourcetype', verbose_name='Loại tài liệu')),
            ],
            options={
                'verbose_name': 'Tài liệu',
                'verbose_name_plural': 'Tài liệu',
                'ordering': ['-created_at'],
            },
        ),
    ]
