# Generated by Django 4.2.27 on 2025-12-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Tên thẻ')),
                ('slug', models.SlugField(unique=True, verbose_name='Đường dẫn')),
            ],
            options={
                'verbose_name': 'Thẻ tag',
                'verbose_name_plural': 'Thẻ tag',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='resources', to='resources.tag', verbose_name='Thẻ tag'),
        ),
    ]
