# Generated by Django 4.2.27 on 2025-12-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_tag_resource_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='external_url',
            field=models.URLField(blank=True, help_text='Link Google Drive, Dropbox, hoặc trang web khác', null=True, verbose_name='Link tài liệu'),
        ),
    ]
