# Generated by Django 4.2.27 on 2025-12-11 06:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0003_resource_external_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_resources', to=settings.AUTH_USER_MODEL, verbose_name='Đã lưu'),
        ),
    ]
