# Generated by Django 4.2.27 on 2025-12-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_resource_bookmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('book', 'Sách'), ('ebook', 'Sách/Ebook'), ('audio', 'Audio'), ('document', 'Tài liệu'), ('pdf', 'PDF'), ('flashcard', 'Flashcard'), ('video', 'Video')], default='document', max_length=20, verbose_name='Loại tài liệu'),
        ),
        migrations.DeleteModel(
            name='ResourceType',
        ),
    ]
